//
//  VC1Configuration.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Swinject
import SwinjectAutoregistration

class VC1Assembly: Assembly {

    public func assemble(container: Container) {

        container.autoregister(IVC1BusinessLogic.self,
						        argument: IVC1DisplayLogic.self,
                                initializer: VC1Interactor.init)
        container.autoregister(IVC1RoutingLogic.self,
						        arguments: VC1ViewController.self, IVC1DataStore.self,
						        initializer: VC1Router.init)

    }
}

class VC1Configurator {
    class func setup(container: Container) {

        container.storyboardInitCompleted(VC1ViewController.self) { _, controller in
            let resolver = assembler.resolver
            let businessLogic = resolver.resolve(IVC1BusinessLogic.self,
									            argument: controller as IVC1DisplayLogic)
            let routingLogic = resolver.resolve(IVC1RoutingLogic.self,
            									arguments: controller, businessLogic as! IVC1DataStore)

            controller.interactor = businessLogic
            controller.router = routingLogic as? (NSObjectProtocol & IVC1DataPassing & IVC1RoutingLogic)
        }
    }
}
