//
//  VC1Interactor.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IVC1BusinessLogic {
    func displayText(request: VC1Models.ShowText.Request)
    func displayTableView()
    func displayTableView2()
    func displayCatalog()
    func displayClient()
    func displayEureka()
}

protocol IVC1DataStore {
    var name: String { get set }
}

class VC1Interactor: IVC1BusinessLogic, IVC1DataStore {
    weak var viewController: IVC1DisplayLogic?
    
    init (viewController: IVC1DisplayLogic?) {
        self.viewController = viewController
    }
    
    internal var name: String = ""
    
    internal func displayText(request: VC1Models.ShowText.Request) {
        name = request.name
        viewController?.routeTo()
    }
    
    internal func displayTableView() {
        viewController?.routeToTableView()
    }
    
    internal func displayTableView2() {
        viewController?.routeToTableView2()
    }
    
    internal func displayCatalog() {
        viewController?.routeToCatalog()
    }
    
    internal func displayClient() {
        viewController?.routeToClient()
    }
    
    internal func displayEureka() {
        viewController?.routeToEureka()
    }
}

