//
//  VC1Router.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IVC1RoutingLogic {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
    func routeToVC2()
    func routeToVC3()
    func routeToVC4()
}

protocol IVC1DataPassing {
    var dataStore: IVC1DataStore? { get }
}

class VC1Router: NSObject, IVC1RoutingLogic, IVC1DataPassing {
    weak var viewController: VC1ViewController?
    var dataStore: IVC1DataStore?
    
    init(viewController: VC1ViewController?, dataStore: IVC1DataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }

    // MARK: Routing

    func routeToVC2() {
        viewController?.performSegue(withIdentifier: "exchangeSegue", sender: nil)
    }
    
    func routeToVC3() {
        viewController?.performSegue(withIdentifier: "tableViewSegue", sender: nil)
    }
    
    func routeToVC4() {
        viewController?.performSegue(withIdentifier: "tableViewSegue2", sender: nil)
    }
    
    // MARK: Navigation

    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "exchangeSegue" {
            guard let viewDestination = segue.destination as? VC2ViewController,
                  var destinationDS = viewDestination.router?.dataStore else {
                return
            }
            destinationDS.name = dataStore?.name ?? ""
        }
        else if segue.identifier == "tableViewSegue" {
            guard let viewDestination = segue.destination as? VC3ViewController,
                  let _ = viewDestination.router?.dataStore else {
                return
            }
        }
        else if segue.identifier == "tableViewSegue2" {
//            guard let viewDestination = segue.destination as? ContactsViewController,
//                  let _ = viewDestination.router?.dataStore else {
//                return
//            }
        }
    }  
}
