//
//  VC1ViewController.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IVC1DisplayLogic: AnyObject {
    func routeTo()
    func routeToTableView()
    func routeToTableView2()
    func routeToCatalog()
}

class VC1ViewController: UIViewController, IVC1DisplayLogic {
    var interactor: IVC1BusinessLogic?
    var router: (NSObjectProtocol & IVC1RoutingLogic & IVC1DataPassing)?

    @IBOutlet weak var textField: UITextField!
    
    @IBAction func buttonPressed(_ sender: Any) {
        updateText()
    }
    
    @IBAction func buttonTableViewPressed(_ sender: Any) {
        interactor?.displayTableView()
    }
    
    @IBAction func buttonTableView2Pressed(_ sender: Any) {
        interactor?.displayTableView2()
    }
    
    @IBAction func catalogButtonpressed(_ sender: Any) {
        interactor?.displayCatalog()
    }
    
    func routeTo() {
        router?.routeToVC2()
    }
    
    func routeToTableView() {
        router?.routeToVC3()
    }
    
    func routeToTableView2() {
        router?.routeToVC4()
    }
    
    func routeToCatalog() {
        router?.routeToCatalog()
    }
    
    func updateText() {
        let name = textField.text!
        let request = VC1Models.ShowText.Request(name: name)
        interactor?.displayText(request: request)
    }
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        self.router?.prepare(for: segue, sender: sender)
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }
}
