//
//  VC2Configuration.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Swinject
import SwinjectAutoregistration

class VC2Assembly: Assembly {

    public func assemble(container: Container) {

        container.autoregister(IVC2BusinessLogic.self,
						        argument: IVC2DisplayLogic.self,
						        initializer: VC2Interactor.init)
        container.autoregister(IVC2RoutingLogic.self,
						        arguments: VC2ViewController.self, IVC2DataStore.self,
						        initializer: VC2Router.init)

    }
}

class VC2Configurator {
    class func setup(container: Container) {
        container.storyboardInitCompleted(VC2ViewController.self) { _, controller in
            let resolver = assembler.resolver
            let businessLogic = resolver.resolve(IVC2BusinessLogic.self,
                                                 argument: controller as IVC2DisplayLogic)
            let routingLogic = resolver.resolve(IVC2RoutingLogic.self,
                                                arguments: controller, businessLogic as! IVC2DataStore)
            
            controller.interactor = businessLogic
            controller.router = routingLogic as? (NSObjectProtocol & IVC2DataPassing & IVC2RoutingLogic)
        }
    }
}
