//
//  VC2Interactor.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IVC2BusinessLogic {
    func showText(request: VC2Models.ShowText.Request)
}

protocol IVC2DataStore {
    var name: String { get set }
}

class VC2Interactor: IVC2BusinessLogic, IVC2DataStore {
    weak var viewController: IVC2DisplayLogic?
    
    internal var name: String = ""
    
    internal func showText(request: VC2Models.ShowText.Request) {
        let response = VC2Models.ShowText.Response(name: name)
        viewController?.displayText(name: response.name)
    }
    
    init(viewController: IVC2DisplayLogic? = nil) {
        self.viewController = viewController
    }
}
