//
//  VC2Router.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IVC2RoutingLogic {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
}

protocol IVC2DataPassing {
    var dataStore: IVC2DataStore? { get }
}

class VC2Router: NSObject, IVC2RoutingLogic, IVC2DataPassing {
    weak var viewController: VC2ViewController?
    var dataStore: IVC2DataStore?
    
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    }
    
    init(viewController: VC2ViewController? = nil, dataStore: IVC2DataStore? = nil) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
}
