//
//  VC2ViewController.swift
//  Tests
//
//  Created by davide on 23/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IVC2DisplayLogic: AnyObject {
    func displayText(name: String)
}

class VC2ViewController: UIViewController, IVC2DisplayLogic {
    var interactor: IVC2BusinessLogic?
    var router: (NSObjectProtocol & IVC2RoutingLogic & IVC2DataPassing)?
    
    @IBOutlet weak var textLabel: UILabel!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        showText()
    }
    
    func showText() {
        let request = VC2Models.ShowText.Request()
        interactor?.showText(request: request)
    }
    
    func displayText(name: String) {
        textLabel.text = name
    }
}

