//
//  VC3Interactor.swift
//  Tests
//
//  Created by davide on 28/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IVC3BusinessLogic {
    func displayTable()
}

protocol IVC3DataStore {
}

class VC3Interactor: IVC3BusinessLogic, IVC3DataStore {
    weak var viewController: IVC3DisplayLogic?
    
    init (viewController: IVC3DisplayLogic?) {
        self.viewController = viewController
    }
    
    internal func displayTable() {
        viewController?.arrayTable = [
            Tests.tableViewModel(name: "Austria", img: "at"),
            Tests.tableViewModel(name: "Belgium", img: "be"),
            Tests.tableViewModel(name: "Germany", img: "de"),
            Tests.tableViewModel(name: "Greece", img: "el"),
            Tests.tableViewModel(name: "France", img: "fr")
        ]
    }
}
