//
//  ContactsModels.swift
//  Tests
//
//  Created by davide on 28/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct tableViewModel: Hashable{
    var name: String
    var img: String?
}

struct tableViewList {
    var allPlaces: [tableViewModel]
}
