//
//  VC3Router.swift
//  Tests
//
//  Created by davide on 28/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IVC3RoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
}

protocol IVC3DataPassing {
    var dataStore: IVC3DataStore? { get }
}

class VC3Router: NSObject, IVC3RoutingLogic, IVC3DataPassing {
    weak var viewController: VC3ViewController?
    var dataStore: IVC3DataStore?

    init(viewController: VC3ViewController?, dataStore: IVC3DataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
    
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    }    
}
